# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-MovableType
version:      1.74
version_from: MovableType.pm
installdirs:  site
requires:
    SOAP::Lite:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
